### ISSUE TITLE
The application crashes when adding letters or symbols in Income (Setting Menu)

### ISSUE THREAD

**Issue by ahyar92** [pmiddend/piggybudget#19]
### Expected behavior
Supposedly, when I add letters or symbols other than the numbers on Income, the application won't crash

### Actual behavior
When I enter the settings menu, and add Income, I accidentally type letters (Not numbers), and suddenly the application crashes and bounces out.

### How to reproduce
1. Open the application
2. Enter the settings menu 
3. In the INCOME section, type letters or symbols (Example : #, *, A, B, or space)
4. Then the error will be seen

### Environment
Tested on 2 devices:

<table>
<thead>
<tr><th>Device</th><th>Android Version</th>
</thead>
<tbody>
<tr><td>VIVO Y81</td><td>Oreo 8.1.0 (CPU: Octa-core Max 2.0 GHz, RAM: 3 GB)</td>
<tr><td>Realmi U1</td><td>Oreo 8.1.0 (Octa-core (4x2.1 GHz Cortex-A73 & 4x2.0 GHz Cortex-A53, RAM: 4 GB)</td>
</table>

---
### Recording Of The Bug
https://youtu.be/j3ruyzfDkCs

### Logcat
```
04-12 16:47:34.342 17428 17475 E AndroidRuntime: FATAL EXCEPTION: ServiceController
04-12 16:47:34.342 17428 17475 E AndroidRuntime: Process: com.vivo.abe, PID: 17428
04-12 16:47:34.342 17428 17475 E AndroidRuntime: java.lang.IllegalArgumentException: unexpected url: asia-rommc-api.vivoglobal.com/v4/messagecenter/messagelist
04-12 16:47:34.342 17428 17475 E AndroidRuntime: 	at okhttp3.Request$Builder.url(Request.java:143)
04-12 16:47:34.342 17428 17475 E AndroidRuntime: 	at com.vivo.sdk.ll1.lll.ll1.ll1ll1lll1(OkHttpRequest.java:41)
04-12 16:47:34.342 17428 17475 E AndroidRuntime: 	at com.vivo.sdk.ll1.lll.ll1.<init>(OkHttpRequest.java:34)
04-12 16:47:34.342 17428 17475 E AndroidRuntime: 	at com.vivo.sdk.ll1.lll.lll.<init>(PostFormRequest.java:31)
04-12 16:47:34.342 17428 17475 E AndroidRuntime: 	at com.vivo.sdk.ll1.l11.ll1.ll1ll1l111(PostFormBuilder.java:21)
04-12 16:47:34.342 17428 17475 E AndroidRuntime: 	at com.vivo.messagecore.net.NetworkHelper.l11(NetworkHelper.java:111)
04-12 16:47:34.342 17428 17475 E AndroidRuntime: 	at com.vivo.messagecore.strategy.periodic.ll1.l11l11111l(PeriodicMessenger.java:117)
04-12 16:47:34.342 17428 17475 E AndroidRuntime: 	at com.vivo.messagecore.strategy.periodic.lll.run(PeriodicMessenger.java:98)
04-12 16:47:34.342 17428 17475 E AndroidRuntime: 	at android.os.Handler.handleCallback(Handler.java:790)
04-12 16:47:34.342 17428 17475 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:99)
04-12 16:47:34.342 17428 17475 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:192)
04-12 16:47:34.342 17428 17475 E AndroidRuntime: 	at android.os.HandlerThread.run(HandlerThread.java:65)
04-12 16:47:34.342 17428 17475 I ABE     : android.os.Process.myPid() = 17428
```

**Comment by pmiddend** [comment]
Oh, I've never tried that, good catch! Will fix it soon.
